package com.ss.ssm.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employees.id
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employees.last_name
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employees.gender
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employees.email
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employees.Department
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    private Integer department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employees.id
     *
     * @return the value of tbl_employees.id
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employees.id
     *
     * @param id the value for tbl_employees.id
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employees.last_name
     *
     * @return the value of tbl_employees.last_name
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employees.last_name
     *
     * @param lastName the value for tbl_employees.last_name
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employees.gender
     *
     * @return the value of tbl_employees.gender
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employees.gender
     *
     * @param gender the value for tbl_employees.gender
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employees.email
     *
     * @return the value of tbl_employees.email
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employees.email
     *
     * @param email the value for tbl_employees.email
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employees.Department
     *
     * @return the value of tbl_employees.Department
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employees.Department
     *
     * @param department the value for tbl_employees.Department
     *
     * @mbg.generated Fri Sep 02 16:49:26 CST 2022
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }
}