package com.ss.ssm.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_department.id
     *
     * @mbg.generated Fri Sep 02 17:07:48 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_department.department_name
     *
     * @mbg.generated Fri Sep 02 17:07:48 CST 2022
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_department.id
     *
     * @return the value of tbl_department.id
     *
     * @mbg.generated Fri Sep 02 17:07:48 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_department.id
     *
     * @param id the value for tbl_department.id
     *
     * @mbg.generated Fri Sep 02 17:07:48 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_department.department_name
     *
     * @return the value of tbl_department.department_name
     *
     * @mbg.generated Fri Sep 02 17:07:48 CST 2022
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_department.department_name
     *
     * @param departmentName the value for tbl_department.department_name
     *
     * @mbg.generated Fri Sep 02 17:07:48 CST 2022
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
}