package com.ss.ssm.dao;

import com.ss.ssm.bean.Employee;
import com.ss.ssm.bean.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);

    List<Employee> selectByExampleWithDepartment(EmployeeExample example);
    Employee selectByIdWithDepartment(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);


    int updateByExampleWithDepartment(@Param("record") Employee record, @Param("example") EmployeeExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employees
     *
     * @mbg.generated Mon Sep 05 13:55:24 CST 2022
     */
    int updateByPrimaryKey(Employee record);
}